### ISSUE TITLE
 module 'winkerberos' has no attribute 'authGSSServerInit'

### ISSUE THREAD

**Issue by lokilak** [mongodb/winkerberos#40]
Hello 

I was trying to test the SSPI server side authentication, but I am getting error that there is attribute for authGSSServerInit, i read the Documentation but was not able to figure it out if we have SSPI server side authentication support or if it is still in progress, any help on this would be much appreciated.

**Comment by behackett** [comment]
I've tagged and published WinKerberos 0.8.0 to pypi. That version includes the server side support. Note that server side support is experimental.
