### ISSUE TITLE
None channel_bindings not supported for authGSSClientStep

### ISSUE THREAD

**Issue by CravateRouge** [mongodb/winkerberos#49]
None is currently not supported when calling:
```
winkerberos.authGSSClientStep(ctx, base64.b64encode(in_token).decode('utf-8'), 
                                        channel_bindings=None) 
TypeError: Expected a channel bindings object
```

I saw a similar issue here: https://bugzilla.redhat.com/show_bug.cgi?id=1354334

**Comment by behackett** [comment]
It works this way to match how ccs-pykerberos works, though I agree it's a bit annoying it you want to write code that might optionally use channel bindings.

**Comment by CravateRouge** [comment]
I understand, I let you close this issue if you estimate it's better to stay that way.
Thanks :)

**Comment by behackett** [comment]
If you would like to send a pull request to have that option accept None, I'd be open to merging it.
